### ISSUE TITLE
Url cutting

### ISSUE THREAD

**Issue by vmakhaev** [ckaznocha/marathon-resource#21]
Installation on DC/OS has url of kind `domain.com/marathon/v2/api`, which is cut to `domain.com/v2/api`. 

Probably problem is [here](https://github.com/ckaznocha/marathon-resource/blob/master/cmd/marathon-resource/marathon/marathon.go#L71)

**Comment by ckaznocha** [comment]
I think your right. I won't be able to fix it until tonight. Probably changing that line to:

``` Go
u.Path = path.Join(u.Path,  path)
```

**Comment by ckaznocha** [comment]
fixed in the latest version
